### ISSUE TITLE
Quelques variables en français

### ISSUE THREAD

**Issue by nicolaslechenic** [dbiron/laboratory#7]
La plupart de tes variables sont bien nommées, cependant j'en vois encore certaines en français : 

https://github.com/dbiron/laboratory/blob/94e256adc639487561fa00525d93d5ee66cb645e/public/js/regex.js#L19

Tu peux aussi régler les problèmes de casse : 

https://github.com/dbiron/laboratory/blob/94e256adc639487561fa00525d93d5ee66cb645e/public/js/regex.js#L7

```js
// Bad
let mavariable;

// Good
let maVariable;
```

**Comment by dbiron** [comment]
ok merci je regarde sa
